[package]
name = "sum"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.10.0"
solana-program = "~1.17.17"

[dev-dependencies]
solana-program-test = "~1.17.17"
solana-sdk = "~1.17.17"

[lib]
name = "sum"
crate-type = ["cdylib", "lib"]